# Script to improve test coverage by writing new tests for identified gaps.
#   Randomly selects a review file that has gaps (and/or low # Checks),
#   writes a new test in the XML to cover one gap, then re-runs coverage
#   analysis. If the new test doesn't improve coverage, it is discarded.
#
# Usage: .\prompts\improve-tests.ps1
#
$prompt = @"
Improve FHIRPath test coverage by writing a new test for an identified gap.

The FHIRPath specification is at: C:\git\hl7\FHIRPath\input\pages\index.md
The test XML file is at: ..\fhir-test-cases\r5\fhirpath\tests-fhir-r5.xml

## Step 1: SELECT a review file

Run ``python scripts/check_coverage.py --list`` to see all features with their gap counts and test counts.
Pick one review file that has gaps (prioritize files with gaps AND low test counts).
Prefer a random-ish selection — don't always pick the first one.

## Step 2: UNDERSTAND the gap

Run ``python scripts/check_coverage.py --file <review-file.md>`` to get the existing tests and coverage analysis.
Read the review file to see the **Gaps:** section — pick ONE gap to address.
Read the relevant section from the specification file (C:\git\hl7\FHIRPath\input\pages\index.md) using the ``spec_header`` field from the coverage output to understand the exact requirement.

If upon reading the spec you determine the gap is actually **untestable** (e.g. the spec defines undefined/implementation-specific behavior, or the requirement concerns runtime environment aspects that cannot be verified deterministically via FHIRPath expressions), you may skip writing a test and instead reclassify it:
- Move the gap description to the ``untestable`` list in the JSON output
- Skip Steps 3 and 4 and proceed directly to Step 5 to update the review file
- This counts as resolving the gap — it will no longer appear as a gap in future runs

## Step 3: WRITE a new test

Add a new ``<test>`` element to the appropriate ``<group>`` in the test XML file.
Follow these rules:
- Find the existing group for this feature (search for the ``testing`` attribute value)
- Choose a unique ``name`` following the group's naming pattern (e.g. ``testStartsWith15``)
- Set ``testing`` to match the feature being tested
- Pick an appropriate ``inputfile`` from available fixtures: ``patient-example.xml``, ``observation-example.xml``, ``questionnaire-example.xml``, ``valueset-example-expansion.xml``, ``patient-example-name.xml``, ``parameters-example-types.xml``, ``patient-example-period.xml``
- Write the ``<expression>`` with proper XML escaping (``&amp;`` for &, ``&lt;`` for <, ``&gt;`` for >)
- Add ``<output>`` elements for each expected result (or none for empty collection)
- For expected-failure tests, add ``invalid="semantic"`` (or ``syntax``/``execution``) on ``<expression>`` and omit ``<output>``
- Add a brief ``description`` attribute explaining what the test verifies, and prefix with `AI:` to indicate it was generated by this script.`
- when testing things like $index, ensure that not just 0 but also other values are tested (e.g. 1) to avoid false positives where the test passes just because $index=0 happens to work.
- ensure that the test result is verified, not that A result is produced. For example, if testing that an expression returns an empty collection, the test should verify that the output is empty, not just that some output is produced.
- if an expression can be verified without using a specific input file, do so. e.g. `{}.empty() = true` could be used to verify an empty collection use works.

Example test structure:
``````xml
<test name="testStartsWith15" testing="startsWith" inputfile="patient-example.xml"
      description="Multiple items in input signals error">
  <expression invalid="semantic">Patient.name.family.startsWith('a')</expression>
</test>
``````

## Step 4: RE-ANALYZE coverage

Now that the test XML has a new test, refresh the coverage analysis using the existing Covered/Gaps as a starting point.

1. Run ``python scripts/check_coverage.py --file <review-file.md>`` to get the updated test list (which now includes your new test).
2. Re-read the relevant specification section (from Step 2).
3. Review the existing Covered/Gaps lists from the review file against the updated test list and specification:
   - Check that the gap you targeted is now covered by the new test (based on the test's ``testing`` attribute and the spec requirement). If not, try to understand why the new test did not cover the gap and either modify the test or pick a different gap.
   - Add the newly covered requirement to the covered list (with the new test name)
   - Remove the targeted gap from the gaps list
   - Check whether any other existing gaps are now also covered by the new test or existing tests that were previously overlooked
   - Check whether the spec has any requirements not captured in either list (add as gaps if found, or as untestable if they cannot be verified via FHIRPath expressions)
   - Preserve existing covered/gap/untestable descriptions that are still accurate — do not discard intentional notes

4. Compare the updated gap list against the old gap list (from Step 2). Confirm that the gap you targeted is no longer in the gaps list. If the gap is still present, remove the test from the XML and try a different approach or pick a different gap.

## Step 5: UPDATE review file and readme

Using the fresh coverage analysis from Step 4, update the review file:
1. Save a JSON file to temp/ with the updated coverage analysis
2. Run ``python scripts/review_set_covered_and_gaps.py --json-file temp/<file>.json``
3. Run ``python scripts/update_test_results.py`` to refresh test results and readme

The JSON format for the coverage update:
{
  "filename": "review-fn-example.md",
  "covered": [
    "Brief description of covered spec requirement (testName1, testName2)"
  ],
  "gaps": [
    "Brief description of spec requirement with no test coverage"
  ],
  "untestable": [
    "Brief description of spec requirement that cannot be verified via FHIRPath expressions"
  ],
  "summary_text": "Brief overall assessment.",
  "reviewed": false
}

Field details:
- covered/gaps/untestable: plain text only (no ✅/❌/⚠️ prefixes — added automatically). Covered items reference test name(s) in parentheses.
- untestable: spec requirements that cannot be verified via FHIRPath test expressions (e.g. logging behavior, UI concerns). These appear under **Covered:** with a ⚠️ marker. Do NOT try to write tests for these — just preserve them.
- summary_text: focus on engine consistency and failure patterns only; leave empty string if nothing notable.
- reviewed: true ONLY when gaps is empty AND 100% pass rate. Otherwise false.

Save intermediate JSON files in the ``temp`` directory.

## Error Handling

If ANY of the following occur, write a file called ``stop.md`` in the repository root with the details and then STOP immediately:

1. **No gaps to process** — if ``python scripts/check_coverage.py --list`` shows zero features with gaps, or you cannot find a gap to target, write stop.md with the message "No gaps remaining to process."
2. **Unable to resolve gap** — if after writing a test the gap count did not decrease and you cannot find an alternative approach, write stop.md explaining which review file and gap could not be resolved and why.
3. **Unexpected errors** — if you encounter invalid/malformed XML, invalid JSON, file-not-found errors, script failures, or any other unexpected error, write stop.md with the error details including the file that caused the problem and the error message.

The stop.md format:
``````markdown
# Stop
Date: <timestamp>
Iteration stopped due to: <reason>

## Details
<detailed explanation of what happened, which files were involved, and any error messages>
``````
"@

copilot --model claude-opus-4.6 --prompt $prompt --allow-tool "shell(python)" --add-dir C:\git\hl7\fhir-test-cases\r5 --allow-all
